default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: BudgetApp_development
  username: postgres

test:
  <<: *default
  database: BudgetApp_test
  username: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  